# conf/train_reranker_config.yaml

model:
  type: 'our_cross_encoder'
  backbone: 'vinai/xphonebert-base'
  max_length: 256

data:
  train_tsv: 'data/train_dataset/train.tsv'
  train_jsonl: 'data/train_dataset/train_g2p.jsonl'
  train_cache: 'data/train_dataset/hard_negative_cache_train.json'
  
  val_tsv: 'data/train_dataset/val.tsv'
  val_jsonl: 'data/train_dataset/val_g2p.jsonl'
  val_cache: 'data/train_dataset/hard_negative_cache_val.json'

training:
  seed: 42
  epochs: 10
  batch_size: 8
  learning_rate: 5.0e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  num_negatives: 4
  
  output_dir: 'outputs/reranker/'
  
  #  로깅 및 저장 주기 제어
  logging_steps: 200      # N 스텝마다 Loss와 LR 터미널 출력
  save_steps: 2000        # N 스텝마다 중간 체크포인트 저장
  eval_steps: 100000      # N 스텝마다 Validation 수행 (큰 값으로 두면 Epoch 끝에서만 수행됨)